title: Harun Armut
author: 
email: harunarmut0@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Personal Notes
show_excerpts: true # set to true to show excerpts on the homepage


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Harun Armut
  tagline: Student - <a href="mailto:harunarmut0@gmail.com">Contact me</a>
  date_format: "%b %-d, %Y"
  style: green
  showNav: false
  showPicker: false
  analytics_id: UA-113157212-4




  # generate social links in footer
  social_links:
    linkedIn: in/harunarmut
    github: harunarmut
    email : harunarmut0@gmail.com
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
